# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config

# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    macos:
      xcode: 13.4.1
    steps:
      - checkout
      # Replace this with steps to build a package, or executable
      - run:
          name: checkout mibap
          command: git clone --recurse-submodules https://github.com/dehesselle/mibap
      - run:
          name: build it
          command: mibap/jhb/usr/bin/bootstrap

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  example:
    jobs:
      - build
